### ISSUE TITLE
arrow 8.0 binary is built without S3 support on RSPM

### ISSUE THREAD

**Issue by cboettig** [rstudio/r-system-requirements#103]
I believe this did not effect arrow 7.0.  This is an optional dependency but very useful.

**Comment by glin** [comment]
S3 support should be there, and we can take a look. From a brief check of the R 4.2 binaries on focal and jammy, I do see S3 support enabled though. Which R version and distribution is this?
```r
# R 4.2 / Ubuntu 20
install.packages("arrow", repos = "https://packagemanager.rstudio.com/cran/__linux__/focal/latest")

arrow::arrow_info()$capabilities
  # dataset substrait   parquet      json        s3  utf8proc       re2    snappy 
  #    TRUE     FALSE      TRUE      TRUE      TRUE      TRUE      TRUE      TRUE 
  #    gzip    brotli      zstd       lz4 lz4_frame       lzo       bz2 
    #  TRUE      TRUE      TRUE      TRUE      TRUE     FALSE      TRUE 
```
```r
# R 4.2 / Ubuntu 22
install.packages("arrow", repos = "https://packagemanager.rstudio.com/cran/__linux__/jammy/latest")

arrow::arrow_info()$capabilities
  # dataset substrait   parquet      json        s3  utf8proc       re2    snappy 
  #    TRUE     FALSE      TRUE      TRUE      TRUE      TRUE      TRUE      TRUE 
  #    gzip    brotli      zstd       lz4 lz4_frame       lzo       bz2 
  #    TRUE      TRUE      TRUE      TRUE      TRUE     FALSE      TRUE 
```

Also, we had an issue with building binaries for arrow 8.0.0 on Ubuntu 20/22 until a day or two ago (https://github.com/apache/arrow/issues/13211). If you're using Ubuntu 20 or 22, could arrow have been installed from source from RSPM (without the S3 support flag enabled)?

**Comment by cboettig** [comment]
Thanks! My apologies for the outdated report!  (yes I'm on 20.04 / focal, looks good now.  (have noticed this issue over the past week or so since the 8.0 release but was on the plane today when a colleague hit the same issue and I hadn't retested)
