### ISSUE TITLE
Cairo on RHEL8.6

### ISSUE THREAD

**Issue by henhell** [rstudio/r-system-requirements#104]
OS: RHEL 8.6
R: 3.5.3 & 4.2.0
According to RSPM Cairo has cairo-devel as prerequisite, I also needed to install libXt-devel to make it compile.

**Comment by glin** [comment]
Thanks for the report. We just asked about this on the Cairo issue tracker and found that libXt was unneeded and will be removed from the next version of Cairo. There's an older issue with more details about this at https://github.com/rstudio/r-system-requirements/issues/31, so I'll close this for now. You can follow https://github.com/rstudio/r-system-requirements/issues/31 for any further updates on Cairo.
