### ISSUE TITLE
Debian support?

### ISSUE THREAD

**Issue by eitsupi** [rstudio/r-system-requirements#111]
It would be great if Debian10 and Debian11 were added as it seems Debian9 was recently removed. #107

Related to r-lib/pak#418

**Comment by glin** [comment]
Hi @eitsupi, this repo did launch with Debian 9 support, but Debian has never actually been supported by RStudio Package Manager. RSPM is the main driver for the supported platforms here, and we don't have any immediate plans to support Debian. 

However, we do internally track feature requests to add Debian support for R binary packages and system requirements, and I'll add this issue to that list. If you any more details about your use case, that would help too. For example, are you running Debian at home or work; are you using the Debian-based Rocker images; are you looking for Debian binary packages as well?

**Comment by eitsupi** [comment]
Thanks for the reply and explanation.
I didn't know the historical background of this repository and your explanation makes sense as to why only Debian 9 was supported.

I usually run R on an Ubuntu-based Docker image to install R binary packages from RSPM.
However, Docker images for many languages are Debian-based, and if we want to install additional R packages on such images, it is useful to have an easy way to check the dependencies of the R packages.
I thought I could do it with pak, but pak probably depends on this repository and seems to have recently lost the ability to do so?

I don't think it distinguishes between Debian and Ubuntu on the general error message if the R package fails to install due to lack of dependent libraries.
So I was just surprised that pak can show the dependent libraries only in the case of Ubuntu.

**Comment by glin** [comment]
Thanks for explaining those use cases, that helps a lot.

RSPM never supported Debian in its system requirements API endpoints, which I believe pak uses, so I'm not sure how pak would've had Debian support unless it was through some other way. (And btw, https://github.com/rstudio/r-system-requirements/pull/107 only removed the CI tests on Debian 9, the existing Debian rules in this repo were kept).

Ubuntu and Debian are similar enough that you could probably use the equivalent Ubuntu release for system requirements in most cases, but there are a few small differences where this wouldn't work:
- when there's no equivalent Debian release for the Ubuntu version. e.g., Ubuntu 22 is based on an unreleased version of Debian, so there are differences like Ubuntu 22 using `libssl3` while Debian 11 only has `libssl1.1`
- when a rule uses an Ubuntu PPA, but this is uncommon and typically only for older Ubuntu versions

You could also consider using R-hub's sysreqsdb, which still actively supports Debian, and has a client API and R package: https://github.com/r-hub/sysreqsdb

**Comment by glin** [comment]
Late update here but we added Debian support a while back, and Package Manager has supported binary packages for Debian as well.
