### ISSUE TITLE
Allow rockylinux 8 ?

### ISSUE THREAD

**Issue by jeroen** [rstudio/r-system-requirements#126]
Currently you allow centos-8 and rockylinux-9. 

https://github.com/rstudio/r-system-requirements/blob/4921b8c2d1d5c5a2e6b4e4415c11bda21b7a9bcc/schema.json#L145-L156

However centos-8 is has reached EOL on december 31st, 2021, whereas rockylinux-8 is supported until 2032. Perhaps we should allow testing with rocky-8?

**Comment by glin** [comment]
We replaced centos-8 with rockylinux-8 a while back, but kept it as centos-8 for backward compatibility. The centos-8 tests are all done on Rocky Linux 8 now, but it looks like we didn't update the README. I can do that now if it helps.

**Comment by glin** [comment]
Updated the docs in #128, and also added more context at https://github.com/rstudio/r-system-requirements/pull/128#issuecomment-1468858161
