### ISSUE TITLE
igrap fails to load in Workbench

### ISSUE THREAD

**Issue by mxshiv** [rstudio/r-system-requirements#129]
After installing the igraph package in R Workbench, it fails to load as it complains of missing library libglpk.so.40. To fix this issue, we need to install a Linux package (rpm). Is there a way where R Workbench can handle the dependencies on its own rather than the IT team install the pre-requisite?

**Comment by szhorvat** [comment]
This is the troubleshooting entry we have on the igraph side for this situation: https://github.com/igraph/rigraph/wiki/Installation-Troubleshooting#libglpkso40-cannot-open-shared-object-file-no-such-file-or-directory Hoping that the frequency of this particular mode of failure could be reduced.

**Comment by krlmlr** [comment]
The short answer is: probably not.

To install GLPK, you typically need sudo (admin) access to the system. While the pak package can install dependencies automatically, it's unlikely that you will get sudo access in your Workbench to be able to benefit from that. But you can try, after installing pak following https://pak.r-lib.org/#arrow_down-installation:

```r
pak::pak("igraph")
```

The other alternative would be to ship our own copy of GLPK with the igraph R package (perhaps statically linked), I'm not sure we want to go that route.

**Comment by gaborcsardi** [comment]
@mxshiv one thing that you could do is querying the system dependencies for the top downloaded packages (or come up with some other criteria, e.g. packages with many reverse dependencies), and tell IT to install all system packages they need. E.g. this gives you the top downloaded packages:
```{r}
pkgsearch::cran_top_downloaded()
```

This is how you can query their system dependencies:
```{r}
❯ writeLines(pak::pkg_system_requirements("igraph", "centos", "7"))
yum install -y epel-release
yum install -y glpk-devel
yum install -y gmp-devel
yum install -y libxml2-devel
```

**Comment by mxshiv** [comment]
Many thanks for your reply. I was able to fix the issue. igraph now works as expected.

**Comment by mxshiv** [comment]
Issue fixed after installing the missing libraries.
