### ISSUE TITLE
Error: package or namespace load failed for ‘slider’:

### ISSUE THREAD

**Issue by mxshiv** [rstudio/r-system-requirements#130]
Hello Team,
    Can you please suggest on the below issue? Thanks.

The R package "slider" fails to load on RStudio Workbench Linux. 

> library(slider) Error: package or namespace load failed for ‘slider’: 
onLoad failed in loadNamespace() for 'slider', details:   
call: fun(libname, pkgname)   
error: function 'obj_is_vector' not provided by package 'vctrs'
>

**Comment by gaborcsardi** [comment]
You possibly don't have the right version of vctrs installed. Try reinstalling vctrs and slider. I have:
```
❯ packageVersion("slider")
[1] ‘0.3.0’

❯ packageVersion("vctrs")
[1] ‘0.6.1’
```

**Comment by mxshiv** [comment]
Yes that was the issue. I reinstalled vctrs package and slider loads without any issue. Many thanks.
