### ISSUE TITLE
load failed for ‘rsparse’ in dyn.load

### ISSUE THREAD

**Issue by mxshiv** [rstudio/r-system-requirements#131]
rsparse fails to load on R Workbench in Linux. I installed the missing rpm "babl" but the issue persists. Can someone please help? Thanks.

> library(rsparse) Error: package or namespace load failed for ‘rsparse’ in dyn.load(file, DLLpath = DLLpath, ...):  
unable to load shared object '/home/mxshiv/R/x86_64-pc-linux-gnu-library/4.2/rsparse/libs/rsparse.so':   
float.so: cannot open shared object file: No such file or directory
>

**Comment by mxshiv** [comment]
I did install the float package but rsparse still cannot load.

> library(float) 
> library(rsparse) 
Loading required package: Matrix 
Error: package or namespace load failed for ‘rsparse’ in dyn.load(file, DLLpath = DLLpath, ...):  
unable to load shared object '/home/mxshiv/R/x86_64-pc-linux-gnu-library/4.2/rsparse/libs/rsparse.so':   
float.so: cannot open shared object file: No such file or directory
> packageVersion("float") 
[1] ‘0.3.1’ 
> packageVersion("rsparse") 
[1] ‘0.5.1’
>

**Comment by mxshiv** [comment]
> library(float)
>

**Comment by gaborcsardi** [comment]
Well, you seem to have a broken installation. It could be some binary incompatibility. So I would try to reinstall all dependencies of rsparse:
```
❯ pak::pkg_deps_tree("rsparse")
rsparse 0.5.1 ✨ ⬇ (3.02 MB)
├─Matrix 1.5-3
│ └─lattice 0.20-45
├─MatrixExtra 0.1.13 ✨ ⬇ (3.53 MB)
│ ├─Matrix
│ ├─Rcpp 1.0.10 ✨
│ ├─RhpcBLASctl 0.23-42 ✨
│ └─float 0.3-1 ✨ ⬇ (900.74 kB)
├─Rcpp
├─data.table 1.14.8 ✨
├─float
├─RhpcBLASctl
└─lgr 0.4.4 ✨ ⬇ (1.38 MB)
  └─R6 2.5.1 ✨
```

**Comment by mxshiv** [comment]
I have reinstalled the dependencies as suggested but no luck yet.

pak::pkg_deps_tree("rsparse")
✔ Loading metadata database ... done
Error:                                                                     
! error in pak subprocess
Caused by error: 
! Could not solve package dependencies:
* rsparse: Can't find package called rsparse.
Type .Last.error to see the more details.
>

**Comment by gaborcsardi** [comment]
I am sorry, what I meant is that you should call `install.packages()` for all those packages, to reinstall them.

**Comment by gaborcsardi** [comment]
So what versions of rsparse and float do you have? Can you also show the output of 
```
install.packages("float")
install.packages("rsparse")
```

**Comment by mxshiv** [comment]
> install.packages("float")
Installing package into ‘/home/mxshiv/R/x86_64-pc-linux-gnu-library/4.2’
(as ‘lib’ is unspecified)
trying URL 'http://x.x.x.x/latest/src/contrib/float_0.3-1.tar.gz'
Content type 'application/x-gzip' length 4971772 bytes (4.7 MB)
==================================================
downloaded 4.7 MB

* installing *binary* package ‘float’ ...
* DONE (float)

The downloaded source packages are in
	‘/tmp/RtmpAJ9Jm6/downloaded_packages’
> install.packages("rsparse")
Installing package into ‘/home/mxshiv/R/x86_64-pc-linux-gnu-library/4.2’
(as ‘lib’ is unspecified)
trying URL 'http://x.x.x./src/contrib/rsparse_0.5.1.tar.gz'
Content type 'application/x-gzip' length 891444 bytes (870 KB)
==================================================
downloaded 870 KB

* installing *binary* package ‘rsparse’ ...
* DONE (rsparse)

The downloaded source packages are in
	‘/tmp/RtmpAJ9Jm6/downloaded_packages’
> packageVersion("rsparse")
[1] ‘0.5.1’
> packageVersion("float")
[1] ‘0.3.1’
>

**Comment by gaborcsardi** [comment]
Can you try to install them from source? Like this:
```
install.packages("float", repos = "https://cran.rstudio.com")
install.packages("rsparse", repos = "https://cran.rstudio.com")
```
or, if you cannot install from CRAN, then this might work:
```
options(HTTPUserAgent = "foobar")
install.packages("float")
install.packages("rsparse")
```

**Comment by glin** [comment]
@mxshiv Are you installing these binary packages from a Package Manager server, and on CentOS or RHEL? If so, I think it's a Package Manager problem. 

`rsparse` is one of those rare packages that take a build-time dependency on another package like `float`:

```r
> install.packages("rsparse", repos = "https://cran.rstudio.com")
trying URL 'https://cran.rstudio.com/src/contrib/rsparse_0.5.1.tar.gz'
Content type 'application/x-gzip' length 212190 bytes (207 KB)
==================================================
downloaded 207 KB

* installing *source* package ‘rsparse’ ...
** package ‘rsparse’ successfully unpacked and MD5 sums checked
** using staged installation
configure: creating ./config.status
config.status: creating src/Makevars
** libs
...
g++ -std=gnu++11 -shared -L/opt/R/4.2.1/lib/R/lib -L/usr/local/lib -o rsparse.so FTRL.o GloVe.o RcppExports.o factorization_machine.o kmeans.o matrix_top_product.o nnls.o rankmf.o utils.o wrmf_explicit.o wrmf_implicit.o wrmf_init.o -fopenmp -L/opt/R/4.2.1/lib/R/library/float/libs -l:float.so -Wl,-rpath=/opt/R/4.2.1/lib/R/library/float/libs -lopenblas -lopenblas -L/opt/R/4.2.1/lib/R/lib -lRlapack -L/opt/R/4.2.1/lib/R/lib -lRblas -lgfortran -lm -lquadmath -L/opt/R/4.2.1/lib/R/lib -lR
installing to /opt/R/4.2.1/lib/R/library/00LOCK-rsparse/00new/rsparse/libs
```

Which means the `rsparse` binaries that Package Manager serves are not portable, since they have hardcoded paths to where `float.so` was installed in the original system. We know of a few other packages like this, but they're mostly unused/deprecated packages that use RcppClassic, so it's never been a big issue.

@gaborcsardi Any ideas for possibly making these types of packages portable? Or should we prevent these types of binaries from being published and always serve source?

@mxshiv For now, I think `rsparse` should work if you install the package from source like @gaborcsardi suggested.

**Comment by gaborcsardi** [comment]
This could be fixed in rsparse, I guess, but short of that, serving the source packages seems like the best solution to me.

**Comment by mxshiv** [comment]
Yes, I was trying to install these packages from our internal Package Manager server and the OS is RHEL 8. The issue finally got fixed after I followed your instructions of installing the source package from the CRAN mirror. Many thanks for your kind help.

> library(float)
> library(rsparse)
Setting OpenMP threads number to 8
Can be adjusted by setting `options("rsparse_omp_threads" = N_THREADS)`
> packageVersion("rsparse")
[1] ‘0.5.1’
> packageVersion("float")
[1] ‘0.3.1’
>

**Comment by glin** [comment]
We have now fixed this in Package Manager by rewriting absolute rpaths to be relative via `$ORIGIN`. So rsparse and similar packages should load now, assuming their dependencies are all installed in the same package library. If this doesn't work for whatever reason, we can still detect non-portable rpaths, and could prevent the binaries from being published instead.
