### ISSUE TITLE
Unable to access index for repository

### ISSUE THREAD

**Issue by mxshiv** [rstudio/r-system-requirements#132]
We have applied proxy settings in our Workbench host (RHEL 8) so that the internal and external HTTP request can go through the proxy. We see that because of the proxy settingss, Workbench is unable to download/install packages from the internal package manager. If proxy settings are disabled, then packages can be installed. 

Have tried adding the exception list as well but no luck.

==========================================================================
Warning in install.packages :
  unable to access index for repository https://x.x.x.x:4242/uat-cran/__linux__/centos8/latest/src/contrib:
  cannot open URL 'https://x.x.x.x:4242/uat-cran/__linux__/centos8/latest/src/contrib/PACKAGES'
Warning in install.packages :
  unable to access index for repository https://x.x.x.x:4242/uat-internal/__linux__/centos8/latest/src/contrib:
  cannot open URL 'https://x.x.x.x:4242/uat-internal/__linux__/centos8/latest/src/contrib/PACKAGES'
Warning in install.packages :
  package ‘tinytex’ is not available for this version of R
=========================================================================

Any suggestions on this would be appreciated.

Many thanks.

**Comment by glin** [comment]
Hi @mxshiv, this repo isn't really meant for general Workbench or Package Manager support outside of the R system requirements info. Can you open a Posit support ticket with this same issue description? You should be able to do that here: https://support.posit.co/hc/en-us/requests/new. From there, we can gather more info and take a look at this proxy issue.

**Comment by mxshiv** [comment]
Thanks @glin. I will reach out to Posit Support.
