### ISSUE TITLE
openbabel rule not triggering with Github Actions

### ISSUE THREAD

**Issue by Aariq** [rstudio/r-system-requirements#141]
I recently contributed a rule for openbabel and eigen3 (#140) and both passed tests and correctly matched the SystemRequirements for the Bioconductor package `ChemmineOB` ("OpenBabel (>= 3.0.0) with headers (http://openbabel.org). Eigen3 with headers.").  However, the `setup-r-dependencies` action is still failing to install `ChemmineOB` due to missing system dependencies.  The action succeeds if I install `libopenbabel-dev` and `libeigen3-dev` manually before `setup-r-dependencies`. I created a test package with only `ChemmineOB` in Imports as a reprex and I'm hoping someone can help explain why the action is still failing.

- [reprex package](https://github.com/Aariq/testpkg)
- [failing action](https://github.com/Aariq/testpkg/actions/runs/5257552406/jobs/9500489504) ([yaml](https://github.com/Aariq/testpkg/blob/main/.github/workflows/R-CMD-check.yaml))
- [working action](https://github.com/Aariq/testpkg/actions/runs/5257552405/jobs/9500489490) ([yaml](https://github.com/Aariq/testpkg/blob/main/.github/workflows/R-CMD-check-manual.yaml))

**Comment by gaborcsardi** [comment]
You need to add a `SystemRequirements` field to the `DESCRIPTION` of your package, that has the pattern that you used in the rule you added to the database.

**Comment by Aariq** [comment]
🤦‍♂️ Ah ok. Sorry, I misunderstood how this works—I was thinking this would look through the `SystemRequirements` fields of all packages in `Imports`

**Comment by Aariq** [comment]
Got it!

**Comment by glin** [comment]
I totally missed the catch with Bioconductor `SystemRequirements`. Public Package Manager does have a Bioconductor repo where you can get those system requirements, but it's separate (and not combinable) from the CRAN repo: https://packagemanager.posit.co/client/#/repos/4/packages/ChemmineOB

To use the API, you also need to supply the Bioconductor version in use:
```sh
$ curl -s "https://packagemanager.posit.co/__api__/repos/4/packages/ChemmineOB/sysreqs?distribution=ubuntu&release=22.04&bioc_version=3.17" | jq
{
  "name": "ChemmineOB",
  "install_scripts": [
    "apt-get install -y libeigen3-dev",
    "apt-get install -y libopenbabel-dev"
  ],
  "dependencies": [
    {
      "name": "BiocGenerics"
    },
    {
      "name": "zlibbioc"
    }
  ]
}
```
@gaborcsardi Could pak use this for Bioconductor dependencies somehow?

**Comment by gaborcsardi** [comment]
> @gaborcsardi Could pak use this for Bioconductor dependencies somehow?

Yes, it will, soon, I created an issue for this: https://github.com/r-lib/pak/issues/507

In the meanwhile you'll need to install them manually, I am afraid.
