### ISSUE TITLE
support alpine linux

### ISSUE THREAD

**Issue by JosiahParry** [rstudio/r-system-requirements#148]
These system requirement are _very_ helpful for building Docker based images. I have recently discovered Alpine linux and would like to use it for R (via https://github.com/r-hub/r-minimal) since it is so lightweight. However, there is no way to know what system dependencies are needed for R packages on Alpine linux. It would be very nice if these r-system-requirements slowly started supportin alpine linux

**Comment by gaborcsardi** [comment]
For the record, we'll still need to add some bits for this to work on the r-minimal images, in particular we need support from pak.
