### ISSUE TITLE
Update rules coverage in README?

### ISSUE THREAD

**Issue by hadley** [rstudio/r-system-requirements#182]
It's starting to feel a bit long in the tooth: "Both tests run with R 3.5.3 for all CRAN packages as of April 4, 2019."

**Comment by glin** [comment]
Addressed in https://github.com/rstudio/r-system-requirements/pull/185,

> Remove the coverage section because it's very old and we haven't done that same test since then. Nowadays we just go off Package Manager's binary coverage, but I'm not sure if that's worth mentioning anymore. The coverage has generally been high for a while now.
