### ISSUE TITLE
Add HarfBuzz

### ISSUE THREAD

**Issue by thomasp85** [rstudio/r-system-requirements#58]
I'd love to have support for HarfBuzz... I'm currently experimenting with it but the plan is that our own graphic devices (e.g. https://github.com/r-lib/ragg) will depend on it.

The experiment currently lives in https://github.com/r-lib/stringshaper which has `harfbuzz` in its SystemRequirements. I would guess that the capitalised spelling should be supported as well (`HarfBuzz`)

**Comment by thomasp85** [comment]
The textshaping package is now on CRAN. It would be great if both HarfBuzz and Fribidi could be detected. What is the best way to move this forward?

**Comment by slopp** [comment]
@thomasp85 do you have enough to go off of based on the docs and examples to create a PR with a rule?

**Comment by thomasp85** [comment]
I can try at least 🙂
