### ISSUE TITLE
Duplicate entries

### ISSUE THREAD

**Issue by robertdj** [rstudio/r-system-requirements#79]
I have noted that there are duplicate entries in `test/sysreqs.json` (for example for the `XML` package). Is this deliberate?

**Comment by jonyoder** [comment]
For reference, XML is on these lines:
https://github.com/rstudio/r-system-requirements/blob/master/test/sysreqs.json#L5026-L5029
https://github.com/rstudio/r-system-requirements/blob/master/test/sysreqs.json#L5074-L5077

**Comment by glin** [comment]
@robertdj Nice catch, the duplicate entries are packages with duplicate entries in CRAN, like XML under the `/Older` path. I think we could add the package version and/or path component to the `sysreqs.json` data to clear up any confusions.

```sh
# https://cran.r-project.org/src/contrib/PACKAGES

Package: XML
Version: 3.99-0.5
Depends: R (>= 4.0.0), methods, utils
Suggests: bitops, RCurl
License: BSD_3_clause + file LICENSE
MD5sum: 0fb0aae42e8340e074bfef9634ac29a1
NeedsCompilation: yes

Package: XML
Version: 3.99-0.3
Depends: R (>= 2.13.0), methods, utils
Suggests: bitops, RCurl
License: BSD_3_clause + file LICENSE
MD5sum: 424ade48afa7ab9da1ba5b9443b565ff
NeedsCompilation: yes
Path: Older
```

**Comment by robertdj** [comment]
Ahh! That makes sense :-) Thanks for clarifying @glin .
