### ISSUE TITLE
chromium on Ubuntu Focal does not fully install

### ISSUE THREAD

**Issue by schloerke** [rstudio/r-system-requirements#86]
When testing `chromium` on Focal within Docker files in https://github.com/rstudio/shinyapps-package-dependencies/pull/302/files#diff-7f5883cd386273c8ef28afb6578002cdc0d27816af32fc681e31178c1137e8e5 , When executed, `chromium` requests to be installed using `snap install chromium` even though the standard `apt-get install chromium-browser` seems to work. 

`snap` installations have difficulty on docker files ([link](https://forum.snapcraft.io/t/unable-to-install-snapcraft-snap-in-docker-image-ubuntu-19-10/13793) to similar error output that I was seeing).

I don't know if we should use the instructions that I was able to achieve in https://github.com/rstudio/shinyapps-package-dependencies/pull/302/files#diff-7f5883cd386273c8ef28afb6578002cdc0d27816af32fc681e31178c1137e8e5R27-R56 , or say that it can not be installed on Focal.

If `r-system-requirements` is already using `snap`, then I believe it could solved using a `post_install` hook. 

-------------------------

Chromium Focal installation related links:
* Why Focal is moving from `deb` to `snap`: https://ubuntu.com/blog/chromium-in-ubuntu-deb-to-snap-transition
* Main website: https://www.chromium.org/getting-involved/download-chromium
* Suggest manual installation instructions: https://github.com/scheib/chromium-latest-linux/tree/4f4e9b85ea02a109e071452de936389cc2fd7376
* GHA instructions: https://github.com/actions/virtual-environments/blob/main/images/linux/scripts/installers/google-chrome.sh#L69-L85

**Comment by glin** [comment]
There aren't any packages on CRAN that have Chromium in `SystemRequirements` today, and I believe Chromium was originally added for Chromote (https://github.com/rstudio/r-system-requirements/pull/48, but @colearendt could confirm). If we add Chrome in https://github.com/rstudio/r-system-requirements/pull/87, could we just remove the Chromium rule? It feels redundant to have both Chrome and Chromium when packages only need one of them, and Chrome looks easier to install.

**Comment by colearendt** [comment]
Yes, that was for Chromium IIRC, paired with this PR: https://github.com/rstudio/chromote/pull/14 . I think there are a few other packages that use Chrom*. 

I suspect the new rule will cover these:
- https://github.com/hrbrmstr/decapitated/blob/205babc38974323d96291f05f99b49f9aac9a6e2/DESCRIPTION#L18
- https://github.com/RLesur/crrri/blob/69c54e657f117b9e30b6a5475604e1e0c6584150/DESCRIPTION#L17

**Comment by schloerke** [comment]
Cool! I'll drop #88 in favor of removing the rule entirely.
